### ISSUE TITLE
[Suggestion] Toggle stamina depletion for jumping

### ISSUE THREAD

**Issue by kckarnige** [TheRedBrain/stamina-attributes#3]
Hi! I'd like to say thank you for making this mod, I LOVE stamina mods in Minecraft, however, I'd like to suggest disabling stamina for jumping.

Minecraft has a LOT of jumping whether it be scaling a mountain or just jumping up a block. Though I understand why jumping drains stamina, it ends up becoming tedious to traverse the most basic of terrain in Minecraft do to having to hop up multiple blocks, and god forbid you use a world generation altering mod like Terralith.

Summary: Stamina drain for jumping makes traversing basic terrain more of a chore than it should be, and it would be nice to have the option to disable it.

**Comment by kckarnige** [comment]
_Also, fun little bonus suggestion concept idea thing,_ maybe speed up stamina regen when the player is crouching while not moving

**Comment by TheRedBrain** [comment]
Hi,

I suggest that you take a look at the server config. Every implemented stamina cost is defined in there.
The entry you are looking for is called "stamina_cost_jumping".
Additionally you may want to disable "jumping_requires_stamina". This controls whether jumping is possible, when stamina is <= 0.

I will probably change the default values so that vanilla gameplay is not altered when just installing the mod. These values are very much depending on the current gameplay. A custom adventure map with roads can support a higher jumping cost than a normal survival game in vanilla terrain.

Also, I will take a look at manipulating regeneration while sneaking/not moving.

Thank you very much for the feedback, the suggestions and for playing with my mod!

**Comment by kckarnige** [comment]
Thank you so much for considering my idea and for helping me with my problem!
